## Day 4 Session 2

It Consist's of all the programs from Day 4 Session 2.

In [1]:
import pandas as pd
import numpy as np

print("--- Introduction to Pandas ---")

# 🔰 Motivation:
# Let's say we receive sensor data like:
# - Sensor A = 25.5°C (temperature)
# - Sensor B = 101.2 kPa (pressure)
# For multiple readings, managing this manually becomes messy.
# Pandas helps organize this kind of tabular data efficiently.

print("Pandas helps organize data like a table (DataFrame) or a single column (Series).")

# ➤ Think of a DataFrame like an Excel table (rows + columns).
# ➤ Think of a Series like a single column from that table.

# We’ll now explore:
# - Series: For 1D labeled data
# - DataFrame: For 2D tabular data

--- Introduction to Pandas ---
Pandas helps organize data like a table (DataFrame) or a single column (Series).

In [2]:
print("--- Pandas Series: Basic Creation Examples ---")

import pandas as pd

# ✅ Example 1: Create a Series from a Python list (default index)
numbers = [10, 20, 30, 40]
series1 = pd.Series(numbers)
print("Series from a list (default index):")
print(series1)
print()

# ✅ Example 2: Create a Series with custom labels (index)
marks = [80, 85, 90]
subjects = ['Math', 'Science', 'English']
series2 = pd.Series(marks, index=subjects)
print("Series with custom index (subject names):")
print(series2)
print()

# ✅ Example 3: Create a Series from a dictionary (keys become index)
fruit_prices = {'Apple': 30, 'Banana': 10, 'Mango': 50}
series3 = pd.Series(fruit_prices)
print("Series from a dictionary:")
print(series3)
print()

# ✅ Example 4: Series with a name (label the data)
temperatures = pd.Series([25.0, 26.5, 27.8], name="Room Temperatures")
print("Series with a name:")
print(temperatures)

--- Pandas Series: Basic Creation Examples ---
Series from a list (default index):
0    10
1    20
2    30
3    40
dtype: int64

Series with custom index (subject names):
Math       80
Science    85
English    90
dtype: int64

Series from a dictionary:
Apple     30
Banana    10
Mango     50
dtype: int64

Series with a name:
0    25.0
1    26.5
2    27.8
Name: Room Temperatures, dtype: float64

In [3]:
print("\n--- Pandas Series: Basic Attributes ---")

import pandas as pd

# Create a simple Series with sensor readings
sensor_readings = pd.Series(
    [10.5, 11.2, 9.8],
    index=['SensorA', 'SensorB', 'SensorC'],
    name='Current_Readings'
)

# Show the Series
print("Sensor Readings Series:")
print(sensor_readings)
print()

# Check useful attributes
print("📌 Index Labels:", sensor_readings.index.tolist())
print("📌 Values Only:", sensor_readings.values)
print("📌 Data Type:", sensor_readings.dtype)
print("📌 Series Name:", sensor_readings.name)
print("📌 Shape (rows,):", sensor_readings.shape)
print("📌 Total Number of Items:", sensor_readings.size)

--- Pandas Series: Basic Attributes ---
Sensor Readings Series:
SensorA    10.5
SensorB    11.2
SensorC     9.8
Name: Current_Readings, dtype: float64

📌 Index Labels: ['SensorA', 'SensorB', 'SensorC']
📌 Values Only: [10.5 11.2  9.8]
📌 Data Type: float64
📌 Series Name: Current_Readings
📌 Shape (rows,): (3,)
📌 Total Number of Items: 3

In [4]:
print("\n--- Pandas Series: Indexing and Slicing (Simple Examples) ---")

import pandas as pd

# Create a Series with fruit prices
fruit_prices = pd.Series(
    [30, 40, 25, 50, 35],
    index=['Apple', 'Banana', 'Orange', 'Mango', 'Grapes']
)

print("Fruit Prices:")
print(fruit_prices)
print()

# Accessing by label
print("Price of Orange:", fruit_prices['Orange'])

# Accessing by position
print("First fruit's price:", fruit_prices[0])

# Slicing by position
print("Prices of 2nd and 3rd fruits (positions 1 to 2):")
print(fruit_prices[1:3])  # Banana, Orange

# Slicing by labels
print("Prices from Banana to Mango:")
print(fruit_prices['Banana':'Mango'])  # Includes Mango

# Selecting multiple fruits by label
print("Prices of Apple and Grapes:")
print(fruit_prices[['Apple', 'Grapes']])

# Boolean Indexing
print("Fruits priced above ₹30:")
print(fruit_prices[fruit_prices > 30])

--- Pandas Series: Indexing and Slicing (Simple Examples) ---
Fruit Prices:
Apple     30
Banana    40
Orange    25
Mango     50
Grapes    35
dtype: int64

Price of Orange: 25
First fruit's price: 30
Prices of 2nd and 3rd fruits (positions 1 to 2):
Banana    40
Orange    25
dtype: int64
Prices from Banana to Mango:
Banana    40
Orange    25
Mango     50
dtype: int64
Prices of Apple and Grapes:
Apple     30
Grapes    35
dtype: int64
Fruits priced above ₹30:
Banana    40
Mango     50
Grapes    35
dtype: int64

/var/folders/r0/q2bxbvrx3hbf3xsp0qjqrkq40000gn/T/ipykernel_20541/1828551555.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("First fruit's price:", fruit_prices[0])

In [5]:
import pandas as pd
import numpy as np

print("--- Pandas DataFrame: Easy Examples ---")

# 🌟 Example 1: Create DataFrame from a dictionary of lists
# Each key becomes a column, and each list holds the values
student_data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Maths_Marks': [85, 90, 78],
    'Science_Marks': [88, 82, 91]
}

df_students = pd.DataFrame(student_data)
print("📊 Students DataFrame (from dictionary of lists):")
print(df_students)
print()

# 🌟 Example 2: Create DataFrame from a list of dictionaries
# Each dictionary represents one row of data
product_data = [
    {'Product': 'Pen', 'Price': 10},
    {'Product': 'Notebook', 'Price': 30},
    {'Product': 'Pencil', 'Price': 5}
]

df_products = pd.DataFrame(product_data)
print("🛒 Products DataFrame (from list of dictionaries):")
print(df_products)
print()

--- Pandas DataFrame: Easy Examples ---
📊 Students DataFrame (from dictionary of lists):
      Name  Maths_Marks  Science_Marks
0    Alice           85             88
1      Bob           90             82
2  Charlie           78             91

🛒 Products DataFrame (from list of dictionaries):
    Product  Price
0       Pen     10
1  Notebook     30
2    Pencil      5

In [6]:
import pandas as pd
import numpy as np

print("\n--- Easy DataFrame Inspection Example ---")

# 🥝 Simple fruit data
fruit_data = {
    'Fruit': ['Apple', 'Banana', 'Mango', 'Orange'],
    'Quantity': [10, 15, 8, 12],
    'Price': [30, 10, 50, 25]
}

df_fruits = pd.DataFrame(fruit_data)
print("Our Fruit DataFrame:\n", df_fruits, "\n")

# 👀 Show first 2 rows
print("First 2 rows:\n", df_fruits.head(2), "\n")

# 👀 Show last 1 row
print("Last row:\n", df_fruits.tail(1), "\n")

# 📋 Quick info about DataFrame
print("Info about DataFrame:")
df_fruits.info()
print()

# 📊 Describe only number columns
print("Summary Statistics:\n", df_fruits.describe(), "\n")

# 📐 Shape (rows, columns)
print("Shape of DataFrame:", df_fruits.shape)

# 📚 Data types of each column
print("Data Types:\n", df_fruits.dtypes, "\n")

# 🔤 Column names
print("Column Names:", df_fruits.columns.tolist())

# 🔢 Row labels (index)
print("Row Labels (Index):", df_fruits.index, "\n")

# 🌧️ Add some missing values
df_with_missing = df_fruits.copy()
df_with_missing.loc[1, 'Quantity'] = np.nan
df_with_missing.loc[3, 'Price'] = np.nan
print("DataFrame with missing values:\n", df_with_missing, "\n")

# ❓ Check how many missing values in each column
print("Missing values count:\n", df_with_missing.isnull().sum())

--- Easy DataFrame Inspection Example ---
Our Fruit DataFrame:
     Fruit  Quantity  Price
0   Apple        10     30
1  Banana        15     10
2   Mango         8     50
3  Orange        12     25

First 2 rows:
     Fruit  Quantity  Price
0   Apple        10     30
1  Banana        15     10

Last row:
     Fruit  Quantity  Price
3  Orange        12     25

Info about DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fruit     4 non-null      object
 1   Quantity  4 non-null      int64
 2   Price     4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

Summary Statistics:
         Quantity     Price
count   4.000000   4.00000
mean   11.250000  28.75000
std     2.986079  16.52019
min     8.000000  10.00000
25%     9.500000  21.25000
50%    11.000000  27.50000
75%    12.750000  35.00000
max    15.000000  50.00000

Shape of DataFrame: (4, 3)
Data Types:
 Fruit       object
Quantity     int64
Price        int64
dtype: object

Column Names: ['Fruit', 'Quantity', 'Price']
Row Labels (Index): RangeIndex(start=0, stop=4, step=1)

DataFrame with missing values:
     Fruit  Quantity  Price
0   Apple      10.0   30.0
1  Banana       NaN   10.0
2   Mango       8.0   50.0
3  Orange      12.0    NaN

Missing values count:
 Fruit       0
Quantity    1
Price       1
dtype: int64

In [7]:
import pandas as pd

# 🍎 Sample data: fruit shop
data = {
    'Fruit': ['Apple', 'Banana', 'Mango', 'Orange'],
    'Quantity': [10, 15, 8, 12],
    'Price': [30, 10, 50, 25],
    'Available': ['Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
print("--- Fruit Shop Data ---")
print(df)

--- Fruit Shop Data ---
    Fruit  Quantity  Price Available
0   Apple        10     30       Yes
1  Banana        15     10       Yes
2   Mango         8     50        No
3  Orange        12     25       Yes

In [8]:
# 1. Select one column
print("Fruit column:\n", df['Fruit'], "\n")

# 2. Select multiple columns
print("Fruit and Price columns:\n", df[['Fruit', 'Price']], "\n")

# 3. Use .loc[row_label, column_name]
print("Fruit at row label 1:", df.loc[1, 'Fruit'])  # Banana

# 4. Use .iloc[row_pos, col_pos]
print("Fruit at row 2, column 0:", df.iloc[2, 0])  # Mango

# 5. Select multiple rows and columns using .loc[]
print("Rows 0-2, Fruit and Quantity:\n", df.loc[0:2, ['Fruit', 'Quantity']], "\n")

# 6. Filter: Show rows where Price > 25
print("Fruits with price > 25:\n", df[df['Price'] > 25], "\n")

# 7. Filter: Show fruits available AND Quantity > 10
filtered_df = df[(df['Available'] == 'Yes') & (df['Quantity'] > 10)]
print("Available fruits with quantity > 10:\n", filtered_df, "\n")

# 8. Update a value using .loc
df_copy = df.copy()
df_copy.loc[2, 'Available'] = 'Yes'
print("After marking Mango as Available:\n", df_copy)

Fruit column:
 0     Apple
1    Banana
2     Mango
3    Orange
Name: Fruit, dtype: object

Fruit and Price columns:
     Fruit  Price
0   Apple     30
1  Banana     10
2   Mango     50
3  Orange     25

Fruit at row label 1: Banana
Fruit at row 2, column 0: Mango
Rows 0-2, Fruit and Quantity:
     Fruit  Quantity
0   Apple        10
1  Banana        15
2   Mango         8

Fruits with price > 25:
    Fruit  Quantity  Price Available
0  Apple        10     30       Yes
2  Mango         8     50        No

Available fruits with quantity > 10:
     Fruit  Quantity  Price Available
1  Banana        15     10       Yes
3  Orange        12     25       Yes

After marking Mango as Available:
     Fruit  Quantity  Price Available
0   Apple        10     30       Yes
1  Banana        15     10       Yes
2   Mango         8     50       Yes
3  Orange        12     25       Yes

In [9]:
import pandas as pd

# 🍓 Simple fruit shop data
data = {
    'Fruit': ['Apple', 'Banana', 'Mango'],
    'Price': [30, 10, 50],
    'Quantity': [5, 8, 3]
}

df = pd.DataFrame(data)
print("--- Original Fruit Shop Data ---")
print(df, "\n")

--- Original Fruit Shop Data ---
    Fruit  Price  Quantity
0   Apple     30         5
1  Banana     10         8
2   Mango     50         3

In [10]:
# 1. Add a new column with the same value for all rows
df['Shop_Name'] = 'FreshFruitMart'
print("Added 'Shop_Name' column:\n", df, "\n")

# 2. Add a new column based on calculation
# Total cost = Price × Quantity
df['Total_Cost'] = df['Price'] * df['Quantity']
print("Added 'Total_Cost' column:\n", df, "\n")

# 3. Change values based on a condition
# If Price > 20, mark as 'Expensive', else 'Cheap'
df['Price_Tag'] = df['Price'].apply(lambda x: 'Expensive' if x > 20 else 'Cheap')
print("Added 'Price_Tag' column:\n", df, "\n")

# 4. Apply a function for custom logic
def stock_status(qty):
    if qty >= 5:
        return 'In Stock'
    else:
        return 'Low Stock'

df['Stock_Status'] = df['Quantity'].apply(stock_status)
print("Added 'Stock_Status' column:\n", df, "\n")

Added 'Shop_Name' column:
     Fruit  Price  Quantity       Shop_Name
0   Apple     30         5  FreshFruitMart
1  Banana     10         8  FreshFruitMart
2   Mango     50         3  FreshFruitMart

Added 'Total_Cost' column:
     Fruit  Price  Quantity       Shop_Name  Total_Cost
0   Apple     30         5  FreshFruitMart         150
1  Banana     10         8  FreshFruitMart          80
2   Mango     50         3  FreshFruitMart         150

Added 'Price_Tag' column:
     Fruit  Price  Quantity       Shop_Name  Total_Cost  Price_Tag
0   Apple     30         5  FreshFruitMart         150  Expensive
1  Banana     10         8  FreshFruitMart          80      Cheap
2   Mango     50         3  FreshFruitMart         150  Expensive

Added 'Stock_Status' column:
     Fruit  Price  Quantity       Shop_Name  Total_Cost  Price_Tag Stock_Status
0   Apple     30         5  FreshFruitMart         150  Expensive     In Stock
1  Banana     10         8  FreshFruitMart          80      Cheap     In Stock
2   Mango     50         3  FreshFruitMart         150  Expensive    Low Stock

In [11]:
import pandas as pd
import numpy as np

# 🎓 Simple student marks data (some values are missing)
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Maths': [90, np.nan, 85, 78],
    'Science': [88, 92, np.nan, np.nan]
}

df = pd.DataFrame(data)
print("--- Original Data ---")
print(df)

--- Original Data ---
   Student  Maths  Science
0    Alice   90.0     88.0
1      Bob    NaN     92.0
2  Charlie   85.0      NaN
3    David   78.0      NaN

In [12]:
df = pd.DataFrame(data)
print("\nOriginal Data:")
print(df)

# Step 2: Check where missing values are
print("\nWhere values are missing (True means missing):")
print(df.isnull())

# Step 3: Count how many missing values per column
print("\nCount of missing values per column:")
print(df.isnull().sum())

# Option A: Drop rows with any missing values
df_dropna = df.dropna()
print("\nDrop rows with missing values:")
print(df_dropna)

# Option B: Fill missing values with 0
df_fill_zero = df.fillna(0)
print("\nFill missing values with 0:")
print(df_fill_zero)

# Option C: Fill missing values with column average (mean)
df_fill_mean = df.copy()
df_fill_mean['Maths'] = df_fill_mean['Maths'].fillna(df_fill_mean['Maths'].mean())
df_fill_mean['Science'] = df_fill_mean['Science'].fillna(df_fill_mean['Science'].mean())
print("\nFill missing values with column mean:")
print(df_fill_mean)

# Option D: Forward fill (copy value from above)
df_ffill = df.fillna(method='ffill')
print("\nForward fill (fill with previous value):")
print(df_ffill)

Original Data:
   Student  Maths  Science
0    Alice   90.0     88.0
1      Bob    NaN     92.0
2  Charlie   85.0      NaN
3    David   78.0      NaN

Where values are missing (True means missing):
   Student  Maths  Science
0    False  False    False
1    False   True    False
2    False  False     True
3    False  False     True

Count of missing values per column:
Student    0
Maths      1
Science    2
dtype: int64

Drop rows with missing values:
  Student  Maths  Science
0   Alice   90.0     88.0

Fill missing values with 0:
   Student  Maths  Science
0    Alice   90.0     88.0
1      Bob    0.0     92.0
2  Charlie   85.0      0.0
3    David   78.0      0.0

Fill missing values with column mean:
   Student      Maths  Science
0    Alice  90.000000     88.0
1      Bob  84.333333     92.0
2  Charlie  85.000000     90.0
3    David  78.000000     90.0

Forward fill (fill with previous value):
   Student  Maths  Science
0    Alice   90.0     88.0
1      Bob   90.0     92.0
2  Charlie   85.0     92.0
3    David   78.0     92.0

/var/folders/r0/q2bxbvrx3hbf3xsp0qjqrkq40000gn/T/ipykernel_20541/1139623056.py:31: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')

In [13]:
import pandas as pd
import numpy as np

print("\n--- Easy Example: Data Cleaning and Transformation ---")

# Step 1: Create a simple DataFrame with "dirty" data
data = {
    'id': ['S1', 'S2', 'S3', 'S4'],
    'score': ['85', '90', 'NA', '75'],  # 'NA' should be treated as missing
    'unit': ['marks', 'marks', 'marks', 'marks'],
    'status': ['ok', 'ok', 'warn', 'error']
}
df = pd.DataFrame(data)
print("\nOriginal Data:")
print(df)

--- Easy Example: Data Cleaning and Transformation ---

Original Data:
   id score   unit status
0  S1    85  marks     ok
1  S2    90  marks     ok
2  S3    NA  marks   warn
3  S4    75  marks  error

In [14]:
# Step 2: Rename columns to be clearer
df = df.rename(columns={
    'id': 'Student_ID',
    'score': 'Exam_Score',
    'unit': 'Score_Unit',
    'status': 'Result_Status'
})
print("\nAfter renaming columns:")
print(df)

# Step 3: Convert 'Exam_Score' to numeric (turn 'NA' to actual missing value)
df['Exam_Score'] = df['Exam_Score'].replace('NA', np.nan)
df['Exam_Score'] = pd.to_numeric(df['Exam_Score'])
print("\nAfter converting 'Exam_Score' to numbers:")
print(df)
print("Data type of 'Exam_Score':", df['Exam_Score'].dtype)

# Step 4: Clean 'Result_Status' - make everything uppercase
df['Result_Status'] = df['Result_Status'].str.upper()
print("\nAfter cleaning 'Result_Status':")
print(df)

After renaming columns:
  Student_ID Exam_Score Score_Unit Result_Status
0         S1         85      marks            ok
1         S2         90      marks            ok
2         S3         NA      marks          warn
3         S4         75      marks         error

After converting 'Exam_Score' to numbers:
  Student_ID  Exam_Score Score_Unit Result_Status
0         S1        85.0      marks            ok
1         S2        90.0      marks            ok
2         S3         NaN      marks          warn
3         S4        75.0      marks         error
Data type of 'Exam_Score': float64

After cleaning 'Result_Status':
  Student_ID  Exam_Score Score_Unit Result_Status
0         S1        85.0      marks            OK
1         S2        90.0      marks            OK
2         S3         NaN      marks          WARN
3         S4        75.0      marks         ERROR

In [15]:
import pandas as pd

print("\n--- Easy GroupBy and Aggregation Example ---")

# Step 1: Create a simple DataFrame
df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Alice', 'Bob', 'Charlie'],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math'],
    'Score': [85, 90, 80, 88, 75]
})
print("Original Data:\n", df, "\n")

# Example 1: Average score per student
avg_score = df.groupby('Student')['Score'].mean()
print("Average Score per Student:\n", avg_score, "\n")

# Example 2: Total score per subject
total_per_subject = df.groupby('Subject')['Score'].sum()
print("Total Score per Subject:\n", total_per_subject, "\n")

# Example 3: Count of entries per student
count_scores = df.groupby('Student')['Score'].count()
print("Number of Scores per Student:\n", count_scores, "\n")

# Example 4: Multiple aggregation per student
summary = df.groupby('Student').agg(
    Max_Score=('Score', 'max'),
    Min_Score=('Score', 'min'),
    Total_Score=('Score', 'sum')
)
print("Summary per Student (Max, Min, Total):\n", summary, "\n")

--- Easy GroupBy and Aggregation Example ---
Original Data:
    Student  Subject  Score
0    Alice     Math     85
1      Bob     Math     90
2    Alice  Science     80
3      Bob  Science     88
4  Charlie     Math     75

Average Score per Student:
 Student
Alice      82.5
Bob        89.0
Charlie    75.0
Name: Score, dtype: float64

Total Score per Subject:
 Subject
Math       250
Science    168
Name: Score, dtype: int64

Number of Scores per Student:
 Student
Alice      2
Bob        2
Charlie    1
Name: Score, dtype: int64

Summary per Student (Max, Min, Total):
          Max_Score  Min_Score  Total_Score
Student
Alice           85         80          165
Bob             90         88          178
Charlie         75         75           75

In [16]:
import pandas as pd

print("\n--- Simple DataFrame Merging Example ---")

# Table 1: Student Marks
marks_df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Maths_Marks': [85, 90, 78]
})

# Table 2: Student Grades
grades_df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'David'],  # 'David' not in marks_df
    'Grade': ['A', 'A+', 'B']
})

print("Marks DataFrame:\n", marks_df, "\n")
print("Grades DataFrame:\n", grades_df, "\n")

# Example 1: Inner Merge - only matching students in both tables
inner_merged = pd.merge(marks_df, grades_df, on='Student', how='inner')
print("Inner Merge (only common students):\n", inner_merged, "\n")

# Example 2: Left Merge - keep all from marks_df
left_merged = pd.merge(marks_df, grades_df, on='Student', how='left')
print("Left Merge (all students from marks_df):\n", left_merged, "\n")

# Example 3: Outer Merge - include all from both
outer_merged = pd.merge(marks_df, grades_df, on='Student', how='outer')
print("Outer Merge (all students from both):\n", outer_merged, "\n")

--- Simple DataFrame Merging Example ---
Marks DataFrame:
    Student  Maths_Marks
0    Alice           85
1      Bob           90
2  Charlie           78

Grades DataFrame:
   Student Grade
0   Alice     A
1     Bob    A+
2   David     B

Inner Merge (only common students):
   Student  Maths_Marks Grade
0   Alice           85     A
1     Bob           90    A+

Left Merge (all students from marks_df):
    Student  Maths_Marks Grade
0    Alice           85     A
1      Bob           90    A+
2  Charlie           78   NaN

Outer Merge (all students from both):
    Student  Maths_Marks Grade
0    Alice         85.0     A
1      Bob         90.0    A+
2  Charlie         78.0   NaN
3    David          NaN     B

In [17]:
import pandas as pd

print("\n--- Time Series Handling (Easiest Example) ---")

# Step 1: Create a small dataset with date strings and temperature values
data = {
    'Date': ['2025-07-01', '2025-07-02', '2025-07-03', '2025-07-04'],
    'Temperature': [30.5, 32.0, 31.2, 29.8]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df, "\n")

# Step 2: Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])
print("After converting 'Date' to datetime:\n", df, "\n")

# Step 3: Set the 'Date' column as the index (helps with time-based operations)
df.set_index('Date', inplace=True)
print("DataFrame with 'Date' as index:\n", df, "\n")

# Step 4: Resample to Weekly Average (though here we only have 4 days)
weekly_avg = df.resample('W').mean()
print("Weekly Average Temperature:\n", weekly_avg, "\n")

# Step 5: Extract Day values using `.index.day`
print("Day of each reading:", df.index.day.tolist())

--- Time Series Handling (Easiest Example) ---
Original DataFrame:
          Date  Temperature
0  2025-07-01         30.5
1  2025-07-02         32.0
2  2025-07-03         31.2
3  2025-07-04         29.8

After converting 'Date' to datetime:
         Date  Temperature
0 2025-07-01         30.5
1 2025-07-02         32.0
2 2025-07-03         31.2
3 2025-07-04         29.8

DataFrame with 'Date' as index:
             Temperature
Date
2025-07-01         30.5
2025-07-02         32.0
2025-07-03         31.2
2025-07-04         29.8

Weekly Average Temperature:
             Temperature
Date
2025-07-06       30.875

Day of each reading: [1, 2, 3, 4]

In [18]:
import pandas as pd

print("\n--- Pandas Categorical Data Handling ---")

# Step 1: Create a simple DataFrame with text-based status values
df_cat = pd.DataFrame({
    'Device_Type': ['Engine', 'Cabin', 'Engine', 'Cabin', 'Engine'],
    'Status': ['OK', 'WARNING', 'OK', 'ERROR', 'OK'],
    'Fault_Code': [101, 201, 101, 301, 101]
})
print("Original DataFrame:\n", df_cat, "\n")
print("Data type of 'Status' before conversion:", df_cat['Status'].dtype, "\n")

--- Pandas Categorical Data Handling ---
Original DataFrame:
   Device_Type   Status  Fault_Code
0      Engine       OK         101
1       Cabin  WARNING         201
2      Engine       OK         101
3       Cabin    ERROR         301
4      Engine       OK         101

Data type of 'Status' before conversion: object

In [19]:
# Step 2: Convert the 'Status' column to a categorical data type
df_cat['Status'] = df_cat['Status'].astype('category')
print("After converting 'Status' to categorical type:\n", df_cat, "\n")
print("New data type of 'Status':", df_cat['Status'].dtype, "\n")

# Step 3: List all the unique categories (labels) Pandas recognized
print("Unique Categories in 'Status':", df_cat['Status'].cat.categories, "\n")

# Step 4: View internal integer codes used for each category (under the hood)
print("Internal Category Codes for each row in 'Status':", df_cat['Status'].cat.codes.tolist(), "\n")

# Step 5: Get count of each category — works efficiently with categorical types
print("Frequency count of each Status value:\n", df_cat['Status'].value_counts(), "\n")

After converting 'Status' to categorical type:
   Device_Type   Status  Fault_Code
0      Engine       OK         101
1       Cabin  WARNING         201
2      Engine       OK         101
3       Cabin    ERROR         301
4      Engine       OK         101

New data type of 'Status': category

Unique Categories in 'Status': Index(['ERROR', 'OK', 'WARNING'], dtype='object')

Internal Category Codes for each row in 'Status': [1, 2, 1, 0, 1]

Frequency count of each Status value:
 Status
OK         3
ERROR      1
WARNING    1
Name: count, dtype: int64

In [20]:
import pandas as pd
import numpy as np
import os  # Used to remove the dummy CSV file at the end

print("\n--- Lab: Analyzing Simple Telemetry Data ---")

# ------------------------------------------------------
# Step 1: Create a dummy CSV file for practice
# ------------------------------------------------------

# Multiline string that represents CSV content
telemetry_csv_content = """Timestamp,Sensor_ID,Temperature_C,Pressure_kPa,Status
2025-07-01 10:00:00,TS-001,25.0,100.0,OK
2025-07-01 10:00:00,PS-001,26.0,98.5,OK
2025-07-01 10:30:00,TS-001,25.2,100.5,OK
2025-07-01 10:30:00,PS-001,27.0,np.nan,WARNING
2025-07-02 09:00:00,TS-001,28.0,101.0,OK
2025-07-02 09:00:00,PS-001,np.nan,102.5,ERROR
2025-07-02 09:30:00,TS-001,28.5,101.2,OK
2025-07-02 09:30:00,PS-001,29.0,103.0,OK
"""

# Save the content to a CSV file (replace 'np.nan' string with actual NaN)
with open("simple_telemetry.csv", "w") as f:
    f.write(telemetry_csv_content.replace("np.nan", str(np.nan)))

print("Dummy CSV file 'simple_telemetry.csv' created.\n")

# ------------------------------------------------------
# Step 2: Load the data into a Pandas DataFrame
# ------------------------------------------------------

try:
    df = pd.read_csv("simple_telemetry.csv")
    print("CSV successfully loaded!\n")
    print("First few rows of the DataFrame:\n", df.head(), "\n")
except FileNotFoundError:
    print("File not found. Ensure the CSV file exists.")
    exit()

# Show column info and data types
print("Data types and non-null counts (df.info()):")
df.info()
print("\n")

# ------------------------------------------------------
# Step 3: Clean the Data
# ------------------------------------------------------

print("--- Cleaning Data ---")

# Convert Timestamp column to datetime objects
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
print("Converted 'Timestamp' to datetime.\n")

# Set Timestamp as index (for time-based analysis)
df.set_index('Timestamp', inplace=True)
print("Set 'Timestamp' as index.\n")

# Ensure temperature values are numeric, then fill missing with column mean
df['Temperature_C'] = pd.to_numeric(df['Temperature_C'], errors='coerce')
avg_temp = df['Temperature_C'].mean()
df['Temperature_C'].fillna(avg_temp, inplace=True)
print(f"Filled missing 'Temperature_C' with mean value: {avg_temp:.2f}\n")

# Ensure pressure values are numeric, then fill missing with column mean
df['Pressure_kPa'] = pd.to_numeric(df['Pressure_kPa'], errors='coerce')
avg_pressure = df['Pressure_kPa'].mean()
df['Pressure_kPa'].fillna(avg_pressure, inplace=True)
print(f"Filled missing 'Pressure_kPa' with mean value: {avg_pressure:.2f}\n")

# Check if any missing values remain
print("Remaining missing values (should be 0):\n", df.isnull().sum(), "\n")

# ------------------------------------------------------
# Step 4: Analyze the Data
# ------------------------------------------------------

print("--- Analyzing Data ---")

# 1. Daily average temperature
daily_avg_temp = df.resample('D')['Temperature_C'].mean()
print("Daily Average Temperatures:\n", daily_avg_temp.round(2), "\n")

# 2. Highest pressure recorded
max_pressure = df['Pressure_kPa'].max()
print(f"Highest Pressure Recorded: {max_pressure:.2f} kPa\n")

# 3. Count how many times status was 'ERROR'
error_count = df[df['Status'] == 'ERROR'].shape[0]
print(f"Total 'ERROR' status entries: {error_count}\n")

# 4. Average pressure per sensor
avg_pressure_by_sensor = df.groupby('Sensor_ID')['Pressure_kPa'].mean()
print("Average Pressure by Sensor:\n", avg_pressure_by_sensor.round(2), "\n")

# ------------------------------------------------------
# Step 5: Summary Report
# ------------------------------------------------------

print("--- Summary Report ---")
print(f"Overall Average Temperature: {df['Temperature_C'].mean():.2f} °C")
print(f"Overall Maximum Pressure: {max_pressure:.2f} kPa")
print(f"Total Error Entries: {error_count}")
print("Daily Temperature Trends:\n", daily_avg_temp.round(2))

# ------------------------------------------------------
# Step 6: Clean Up (Remove Dummy File)
# ------------------------------------------------------

os.remove("simple_telemetry.csv")
print("\nDummy file 'simple_telemetry.csv' has been deleted.")

--- Lab: Analyzing Simple Telemetry Data ---
Dummy CSV file 'simple_telemetry.csv' created.

CSV successfully loaded!

First few rows of the DataFrame:
              Timestamp Sensor_ID  Temperature_C  Pressure_kPa   Status
0  2025-07-01 10:00:00    TS-001           25.0         100.0       OK
1  2025-07-01 10:00:00    PS-001           26.0          98.5       OK
2  2025-07-01 10:30:00    TS-001           25.2         100.5       OK
3  2025-07-01 10:30:00    PS-001           27.0           NaN  WARNING
4  2025-07-02 09:00:00    TS-001           28.0         101.0       OK

Data types and non-null counts (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Timestamp      8 non-null      object
 1   Sensor_ID      8 non-null      object
 2   Temperature_C  7 non-null      float64
 3   Pressure_kPa   7 non-null      float64
 4   Status         8 non-null      object
dtypes: float64(2), object(3)
memory usage: 452.0+ bytes


--- Cleaning Data ---
Converted 'Timestamp' to datetime.

Set 'Timestamp' as index.

Filled missing 'Temperature_C' with mean value: 26.96

Filled missing 'Pressure_kPa' with mean value: 100.96

Remaining missing values (should be 0):
 Sensor_ID        0
Temperature_C    0
Pressure_kPa     0
Status           0
dtype: int64

--- Analyzing Data ---
Daily Average Temperatures:
 Timestamp
2025-07-01    25.80
2025-07-02    28.11
Freq: D, Name: Temperature_C, dtype: float64

Highest Pressure Recorded: 103.00 kPa

Total 'ERROR' status entries: 1

Average Pressure by Sensor:
 Sensor_ID
PS-001    101.24
TS-001    100.68
Name: Pressure_kPa, dtype: float64

--- Summary Report ---
Overall Average Temperature: 26.96 °C
Overall Maximum Pressure: 103.00 kPa
Total Error Entries: 1
Daily Temperature Trends:
 Timestamp
2025-07-01    25.80
2025-07-02    28.11
Freq: D, Name: Temperature_C, dtype: float64

Dummy file 'simple_telemetry.csv' has been deleted.

/var/folders/r0/q2bxbvrx3hbf3xsp0qjqrkq40000gn/T/ipykernel_20541/381971093.py:63: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Temperature_C'].fillna(avg_temp, inplace=True)
/var/folders/r0/q2bxbvrx3hbf3xsp0qjqrkq40000gn/T/ipykernel_20541/381971093.py:69: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pressure_kPa'].fillna(avg_pressure, inplace=True)